version: 2

aliases:
  - &install-pnpm
    run:
      name: Install pnpm
      command: sudo npm install --global pnpm
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: yarn
  - &build-packages
    run:
      name: Build
      command: yarn build
  - &run-unit-tests
    run:
      name: Test
      command: yarn test

jobs:
  build:
    working_directory: ~/kunlun-cli
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - *install-pnpm
      - *restore-cache
      - *install-deps
      - *save-cache
      - *build-packages

  unit_tests:
    working_directory: ~/kunlun-cli
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - *install-pnpm
      - *restore-cache
      - *install-deps
      - *build-packages
      - *run-unit-tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
